Homework 16 02 20 remastered
cofano88/Landing-TMS pull request #2
Opened 2020-02-17 18:15 UTC by cofano88

2020-02-17 19:37 UTC, tpotapchik requested changes

2020-02-17 19:37 UTC, tpotapchik commented on assets/css/style.css
> +  /* margin-block-start: 0;
Remove it if you don't need it

2020-02-17 19:37 UTC, tpotapchik commented on assets/css/style.css
> +    url(../img/header.jpg);
Add no-repeat

2020-02-17 19:37 UTC, tpotapchik commented on assets/css/style.css
> +  background-repeat: no-repeat;
Seems you don't need itnow

2020-02-17 19:37 UTC, tpotapchik commented on assets/css/style.css
> +  margin-left: 565px;
suspicious value

2020-02-17 19:37 UTC, tpotapchik commented on assets/css/style.css
> +  margin-top: 0;
If you don't want to use origin margin value you can define it at the top

*{margin:0;}

2020-02-17 19:37 UTC, tpotapchik commented on assets/css/style.css
> +    url(../img/custom.jpg);
Add no-repeat

2020-02-17 19:37 UTC, tpotapchik commented on index.html
> +          <div class="review clearfix">
Why clearfix here?

2020-02-18 15:29 UTC, cofano88 commented on index.html
> +          <div class="review clearfix">
Because it have 3 float elements

2020-02-18 15:35 UTC, cofano88 commented on index.html
> +          <div class="review clearfix">
sorry, just found it) My fail.

2020-02-19 11:15 UTC, merged